# Generated by Django 2.0.5 on 2020-05-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200526_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20, verbose_name='Статус'),
        ),
    ]
